services:
  - type: web
    name: python-scraping-to-make
    env: docker
    plan: free
    repo: https://github.com/RonaldAllanRivera/python-scraping-to-make.git
    branch: main
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - requirements.txt
    autoDeploy: true
